### ISSUE TITLE
Cisco Duo Web SDK v2 is outdated

### ISSUE THREAD

**Issue by Ondjultomte** [itiligent/Guacamole-Installer#50]
When installing with this script the Web SDK v2 seems to be used. its depricated now.  Web SDK v4 needs to be used

We are stuck with this message when deploying the script and setting up Duo.

![image](https://github.com/user-attachments/assets/1b633d07-f05b-4aa4-8ee8-bc0952688ef8)

**Comment by itiligent** [comment]
This this looks like DUO giving themselves (and their users) an uppercut by changing the front end prompt functionality but not considering things outside of their own preferred use case and taking away from users any control to keep the legacy prompt after April this year - because nobody is ever going to need legacy software right? :-(

you've got wo options:
1. see https://duo.com/docs/universal-prompt-update-guide - This link suggests talking to Duo suppot for apps that have not yet been updated which means there might be a manual override for the date limitation on the Web SDK config, but they want to force poeple down a certain track wherever they can first maybe??

2. Or wait for Guacmole 1.6 as this issue is in the pipline. see here: https://issues.apache.org/jira/browse/GUACAMOLE-1289?jql=text%20~%20%22duo%22 The notes on the issue suggest that code has alredy been added to fix this, so of you have the skills you could build guac from the latest snaphot verion to test. 
 
Not much I can do I'm afraid, but do please share any progress you make here to help others as this is a more serious issue than many.

**Comment by itiligent** [comment]
closing as this is a Guac +  Duo issue that is slated to be fixed in 1.6, but please feel free to add details of any workarounds you find or your progress with Duo support here

**Comment by Ondjultomte** [comment]
Hi, thanks for the links.

 yes I know, maybe a disclamer text  or something ? but 1.6 might be just  around the corner .

**Comment by Ondjultomte** [comment]
just adding some info here, Guac v1.6 likely release in Oct.
